# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edited_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('predicted_outcome', models.TextField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_datetime', models.DateTimeField()),
                ('home_team', models.TextField(max_length=255)),
                ('away_team', models.TextField(max_length=255)),
                ('result', models.TextField(blank=True, default=b'', max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('exact_score', models.NullBooleanField(help_text=b"Indicating, whether user've predicted an exact result")),
                ('exact_outcome', models.NullBooleanField(help_text=b"Indicating, whether user've predicted an exact outcome")),
                ('points', models.IntegerField(default=0)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epl_bot.Bet')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, unique=True)),
                ('stadium', models.TextField(max_length=255)),
                ('logo', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epl_bot.Fixture'),
        ),
    ]
